# configs/model/cifar_densenet.yaml
# CIFAR-10 DenseNet 模型配置

_target_: src.models.cifar_module.CIFARModule

model_name: DenseNet
model_hparams:
  num_classes: 10
  num_layers: [6, 6, 6, 6]
  bn_size: 2
  growth_rate: 16
  act_fn_name: relu

optimizer_name: Adam
optimizer_hparams:
  lr: 1e-3
  weight_decay: 1e-4

